### PR TITLE
New idea: Variable Sets

### PR DESCRIPTION
**Pull request by kitbs**
Hi @dillingham

Hope you don't mind me chipping in again on this package. I honestly have been looking out for something like this forever, so might be a little overexcited. 😬 

I had the idea to make a reusable way of turning a single variable value into a dynamic set of variables which are transformed in predictable ways. For example, you would take a model name and turn it into a class name, table name, permission key name, package name, translation key, etc., e.g:

```
"Blog Post" becomes "BlogPost", "blog_posts", "blog-posts", ...
```

I have called this a "variable set", although I'm totally not sold on the name. The idea is you create a single-purpose but reusable class that takes a single value and transforms it in various ways and creates dynamic variables from it.

This would save you needing to separately and manually define every variation of "blog post" in the example above as a separate variable. And it would make generating Laravel and Nova classes/packages more dynamic, if a single model name and was able to be extrapolated to every file name and class name required.

I've updated the readme to explain it better, and also updated the Render console command to support it. I didn't think the use case fit any of the other commands as well, but let me know what you think.

Cheers

### CODE REVIEW

**Comment by dillingham** [comment]
```php
<?php

namespace Stub;

class Formatter
{
    public $variables;

    public function __construct($variables)
    {
        $this->variables = $variables;
    }

    public function __get($attribute)
    {
        if (isset($this->variables[$attribute])) {
            return $this->variables[$attribute];
        }
    }

    public function __invoke()
    {
        $computed = [];

        $methods = array_diff(
            get_class_methods(get_called_class()),
            get_class_methods(get_class()),
        );

        foreach ($methods as $method) {
            $computed[$method] = $this->$method();
        }

        return $computed;
    }
}
```

What do you think about maybe doing it this way?

```php
<?php

namespace Tests\Formatters;

use Stub\Formatter;

class Repository extends Formatter
{
    public function title()
    {
        return $this->package;
    }
}
```

```php
(new Stub)
    ->source('stubs/stub-1')
    ->output('project')
    ->render(new Repository([
        'package' => 'Package Name',
    ]));
```

**Comment by kitbs** [comment]
Yeah, I like the simplicity of it and had tossed around an idea of using the method names somehow like this, just wasn't quite sure how to approach it.

I can think of one pitfall of assuming every method on the extended class is intended to be a variable. I think `get_class_methods()` will return protected/private methods as well, if called within a class. If the user has added any helper methods to the class that take arguments, they would foul up at `$this->$method()`. Maybe a similar thing could be done with reflection and filtering out only public methods and methods with no arguments?

One thing that this solution doesn't do is return the original passed variables without modification along with the derived variables. I'm thinking you could pass in some variables that should be included in the transforms as well as others that you just want to include as-is. If you changed the first line of the `__invoke()` to `$computed = $this->variables;`, that would merge them in nicely, and then allow them to be overridden by a transform if a method with the same name is used.

**Comment by dillingham** [comment]
I hadn't considered the private helpers..
Just tested it and surprisingly they are omitted from the $computed haha

And you're right, having non computed passed in and returned is important
Adding the adjustment you suggested works elegantly.

```php
<?php

namespace Stub;

use ReflectionClass;

class Formatter
{
    public $variables;

    public function __construct($variables)
    {
        $this->variables = $variables;
    }

    public function __get($attribute)
    {
        if (isset($this->variables[$attribute])) {
            return $this->variables[$attribute];
        }
    }

    public function __invoke()
    {
        $computed = $this->variables;

        $methods = array_diff(
            get_class_methods(get_called_class()),
            get_class_methods(get_class()),
        );

        foreach ($methods as $method) {
            $computed[$method] = $this->$method();
        }

        return $computed;
    }
}

```

**Comment by kitbs** [comment]
Your idea is definitely cleaner. I think because this branch has got quite out of sync from the master, it'll be cleaner to start a new branch and PR. I'll try to reimplement this using your approach.

**Pull request closed without merging**
